language: java
jdk: oraclejdk8
sudo: false # faster builds
branches:
  only:
    - develop
install: true
script:
  - "mvn clean package cobertura:cobertura coveralls:report -DrepoToken=$COVERALLS_TOKEN -P soc-modules-development,installPackage"
cache:
  directories:
  - "$HOME/.m2"
