language: java
jdk: oraclejdk8
sudo: false # faster builds
branches:
  only:
    - master
    - develop
script:
  - "mvn clean install"
  - "mvn test"
  - "mvn cobertura:cobertura"
cache:
  directories:
  - "$HOME/.m2"
after_success:
  - bash <(curl -s https://codecov.io/bash)