language: java
jdk: oraclejdk8
sudo: false # faster builds
env:
  matrix:
    - SOC_BUILD_PROFILE=soc-modules
script:
  - "mvn clean install -P ${SOC_BUILD_PROFILE}"
  - "mvn test -P ${SOC_BUILD_PROFILE}"
  - "mvn cobertura:cobertura -P ${SOC_BUILD_PROFILE}"
cache:
  directories:
  - "$HOME/.m2"
after_success:
  - bash <(curl -s https://codecov.io/bash)