language: java
jdk: oraclejdk8
sudo: false # faster builds
branches:
  only:
    - master
    - develop
script:
  - "mvn cobertura:cobertura coveralls:report clean install -DrepoToken=$COVERALLS_TOKEN"
cache:
  directories:
  - "$HOME/.m2"
