language: java
jdk: oraclejdk8
sudo: false # faster builds
branches:
  only:
    - master
    - develop
script:
  - "mvn -DrepoToken=$COVERALLS_TOKEN clean install cobertura:cobertura coveralls:report"
cache:
  directories:
  - "$HOME/.m2"
